# Generated by Django 3.0.7 on 2021-02-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('image_name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='home/static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('image_name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='home/static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('image_name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='home/static/images')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('image_name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='home/static/images')),
                ('tool', models.ManyToManyField(help_text='Tool used in the Job', to='home.Tool')),
            ],
        ),
    ]
